package analyzer

import (
	"go/parser"
	"go/token"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Test constants removed - using IssueType enum instead

func TestAIBullshitAnalyzer_DetectsOverEngineering(t *testing.T) {
	code := `
package test

// Factory for simple addition - AI bullshit
type NumberAdderFactory interface {
	CreateNumberAdder() NumberAdderStrategy
}

type NumberAdderStrategy interface {
	AddNumbers(a, b int) int
}

type SimpleNumberAdderFactory struct{}

func (f *SimpleNumberAdderFactory) CreateNumberAdder() NumberAdderStrategy {
	return &SimpleNumberAdderStrategy{}
}

type SimpleNumberAdderStrategy struct{}

func (s *SimpleNumberAdderStrategy) AddNumbers(a, b int) int {
	return a + b
}
`

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "test.go", code, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}

	analyzer := NewAIBullshitAnalyzer()
	issues := analyzer.Analyze(file, fset)

	// Should detect Factory pattern for simple operation
	found := false
	for _, issue := range issues {
		if issue.Type == IssueAIOverengineeredSimple {
			found = true
			break
		}
	}

	if !found {
		t.Error("Expected to find AI_OVER_ENGINEERING issue for Factory pattern")
	}
}

func TestCheckUnnecessaryComplexity(t *testing.T) {
	tests := []struct {
		name     string
		code     string
		expected []string // expected issue types
	}{
		{
			name: "simple function with unnecessary interfaces",
			code: `package main
type Calculator interface {
	Add(a, b int) int
}

type SimpleCalculator struct{}

func (s *SimpleCalculator) Add(a, b int) int {
	return a + b
}

func main() {
	calc := &SimpleCalculator{}
	result := calc.Add(1, 2)
	_ = result
}`,
			expected: []string{"AI_OVER_ABSTRACTION"},
		},
		{
			name: "deeply nested function",
			code: `package main
func process() {
	if true {
		if true {
			if true {
				if true {
					if true {
						if true {
							println("deeply nested")
						}
					}
				}
			}
		}
	}
}`,
			expected: []string{"AI_DEEP_NESTING"},
		},
		{
			name: "multiple returns in simple function",
			code: `package main
func getValue(x int) int {
	if x > 10 {
		return 10
	}
	if x > 5 {
		return 5
	}
	if x > 0 {
		return 1
	}
	return 0
}`,
			expected: []string{},
		},
		{
			name: "factory with builder pattern",
			code: `package main
type Builder interface {
	Build() Product
}

type Factory interface {
	Create() Builder
}

type Product struct {
	value int
}

type ConcreteBuilder struct{}

func (b *ConcreteBuilder) Build() Product {
	return Product{value: 1}
}

type ConcreteFactory struct{}

func (f *ConcreteFactory) Create() Builder {
	return &ConcreteBuilder{}
}`,
			expected: []string{"AI_PATTERN_OVERUSE"},
		},
		{
			name: "singleton pattern",
			code: `package main
type Singleton struct{}

var instance *Singleton

func GetInstance() *Singleton {
	if instance == nil {
		instance = &Singleton{}
	}
	return instance
}`,
			expected: []string{"AI_PATTERN_OVERUSE"},
		},
		{
			name: "many small functions",
			code: `package main
func add1(x int) int { return x + 1 }
func add2(x int) int { return x + 2 }
func add3(x int) int { return x + 3 }
func add4(x int) int { return x + 4 }
func add5(x int) int { return x + 5 }
func add6(x int) int { return x + 6 }
func add7(x int) int { return x + 7 }
func add8(x int) int { return x + 8 }
func add9(x int) int { return x + 9 }
func add10(x int) int { return x + 10 }
func add11(x int) int { return x + 11 }`,
			expected: []string{"AI_MANY_SMALL_FUNCS"},
		},
	}

	for _, tt := range tests {
		t.Run(
			tt.name, func(t *testing.T) {
				fset := token.NewFileSet()
				file, err := parser.ParseFile(fset, "test.go", tt.code, parser.ParseComments)
				require.NoError(t, err)

				analyzer := NewAIBullshitAnalyzer()
				issues := analyzer.Analyze(file, fset)

				issueTypes := make(map[string]bool)
				for _, issue := range issues {
					issueTypes[issue.Type.String()] = true
				}

				for _, expected := range tt.expected {
					assert.True(t, issueTypes[expected], "Expected issue %s not found", expected)
				}
			},
		)
	}
}

func TestCheckAIPatterns(t *testing.T) {
	tests := []struct {
		name        string
		commentText string
		shouldMatch bool
	}{
		{
			name:        "AI-generated comment",
			commentText: "// This function was generated by AI",
			shouldMatch: true,
		},
		{
			name:        "Copilot comment",
			commentText: "// Copilot suggested this implementation",
			shouldMatch: true,
		},
		{
			name:        "ChatGPT comment",
			commentText: "// ChatGPT helped write this",
			shouldMatch: true,
		},
		{
			name:        "normal comment",
			commentText: "// Calculate the sum of two numbers",
			shouldMatch: false,
		},
	}

	for _, tt := range tests {
		t.Run(
			tt.name, func(t *testing.T) {
				code := `package main
` + tt.commentText + `
func test() {
	println("test")
}`
				fset := token.NewFileSet()
				file, err := parser.ParseFile(fset, "test.go", code, parser.ParseComments)
				require.NoError(t, err)

				analyzer := NewAIBullshitAnalyzer()
				issues := analyzer.Analyze(file, fset)

				found := false
				for _, issue := range issues {
					if issue.Type == IssueAIGeneratedComment {
						found = true
						break
					}
				}

				assert.Equal(t, tt.shouldMatch, found, "AI pattern detection mismatch for: %s", tt.commentText)
			},
		)
	}
}

func TestAIBullshitAnalyzer_DetectsUnnecessaryGoroutines(t *testing.T) {
	code := `
package test

func AddNumbers(a, b int) int {
	resultCh := make(chan int, 1)
	
	go func() {
		resultCh <- a + b
	}()
	
	return <-resultCh
}
`

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "test.go", code, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}

	analyzer := NewAIBullshitAnalyzer()
	issues := analyzer.Analyze(file, fset)

	// Should detect unnecessary goroutines
	found := false
	for _, issue := range issues {
		if issue.Type == IssueAIGoroutineOverkill {
			found = true
			break
		}
	}

	if !found {
		t.Error("Expected to find AI_GOROUTINE_OVERKILL issue")
	}
}

func TestAIBullshitAnalyzer_DetectsUnnecessaryReflection(t *testing.T) {
	code := `
package test

import "reflect"

func GetValue(x int) int {
	val := reflect.ValueOf(x)
	return int(val.Int())
}
`

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "test.go", code, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}

	analyzer := NewAIBullshitAnalyzer()
	issues := analyzer.Analyze(file, fset)

	// Should detect unnecessary reflection
	found := false
	for _, issue := range issues {
		if issue.Type == IssueAIUnnecessaryReflection {
			found = true
			break
		}
	}

	if !found {
		t.Error("Expected to find AI_UNNECESSARY_REFLECTION issue")
	}
}

func TestAIBullshitAnalyzer_DetectsUnnecessaryInterfaces(t *testing.T) {
	code := `
package test

type Handler interface {
	Handle(data string)
}

type Manager interface {
	Manage()
}

type Provider interface {
	Provide() int
}
`

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "test.go", code, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}

	analyzer := NewAIBullshitAnalyzer()
	issues := analyzer.Analyze(file, fset)

	// Should detect generic interface names
	interfaceIssues := 0
	for _, issue := range issues {
		if issue.Type == IssueAIUnnecessaryInterface {
			interfaceIssues++
		}
	}

	if interfaceIssues < 3 {
		t.Errorf("Expected at least 3 AI_UNNECESSARY_INTERFACE issues, got %d", interfaceIssues)
	}
}

func TestAIBullshitAnalyzer_IgnoresLegitimatePatterns(t *testing.T) {
	code := `
package test

import (
	"context"
	"sync"
)

// Legitimate use of goroutines for parallel processing
func ProcessItems(items []string) []string {
	var wg sync.WaitGroup
	results := make([]string, len(items))
	
	for i, item := range items {
		wg.Add(1)
		go func(idx int, val string) {
			defer wg.Done()
			// Simulate expensive operation
			results[idx] = processItem(val)
		}(i, item)
	}
	
	wg.Wait()
	return results
}

func processItem(item string) string {
	// Expensive processing
	return item
}

// Legitimate Factory for complex object creation
type DatabaseConnectionFactory interface {
	CreateConnection(ctx context.Context, config Config) (Connection, error)
}

type Config struct {
	Host     string
	Port     int
	Database string
}

type Connection interface {
	Query(ctx context.Context, sql string) error
	Close() error
}
`

	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "test.go", code, parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}

	analyzer := NewAIBullshitAnalyzer()
	issues := analyzer.Analyze(file, fset)

	// Should not detect issues for legitimate patterns
	for _, issue := range issues {
		if issue.Type == IssueAIGoroutineOverkill {
			t.Error("Should not flag legitimate goroutine usage")
		}
		if issue.Type == IssueAIOverengineeredSimple && issue.Line < 30 {
			t.Error("Should not flag legitimate factory pattern for complex objects")
		}
	}
}

func BenchmarkAIBullshitAnalyzer(b *testing.B) {
	code := `
package test

type Factory interface {
	Create() Strategy
}

type Strategy interface {
	Execute() int
}

func DoWork(x int) int {
	ch := make(chan int)
	go func() { ch <- x * 2 }()
	return <-ch
}
`

	fset := token.NewFileSet()
	file, _ := parser.ParseFile(fset, "test.go", code, parser.ParseComments)
	analyzer := NewAIBullshitAnalyzer()

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = analyzer.Analyze(file, fset)
	}
}

func FuzzAIBullshitAnalyzer(f *testing.F) {
	// Add seed corpus
	f.Add(
		`package test
func Add(a, b int) int { return a + b }`,
	)

	f.Add(
		`package test
type Factory interface { Create() interface{} }`,
	)

	f.Add(
		`package test
import "reflect"
func Get(x int) int { return reflect.ValueOf(x).Interface().(int) }`,
	)

	f.Fuzz(
		func(t *testing.T, code string) {
			fset := token.NewFileSet()
			file, err := parser.ParseFile(fset, "test.go", code, parser.ParseComments)
			if err != nil {
				// Invalid Go code, skip
				return
			}

			analyzer := NewAIBullshitAnalyzer()
			// Should not panic
			_ = analyzer.Analyze(file, fset)
		},
	)
}
