package analyzer

import (
	"fmt"
	"go/ast"
	"go/token"
	"strings"
)

// AIBullshitAnalyzer detects AI-generated bullshit code patterns
type AIBullshitAnalyzer struct {
	name string
}

// NewAIBullshitAnalyzer creates a new AI bullshit detector
func NewAIBullshitAnalyzer() Analyzer {
	return &AIBullshitAnalyzer{
		name: "AI Bullshit Detector",
	}
}

func (a *AIBullshitAnalyzer) Name() string {
	return a.name
}

func (a *AIBullshitAnalyzer) Analyze(node interface{}, fset *token.FileSet) []*Issue {
	var issues []*Issue

	astNode, ok := node.(ast.Node)
	if !ok {
		return issues
	}

	// Check file-level comments for AI patterns
	if file, ok := astNode.(*ast.File); ok {
		for _, cg := range file.Comments {
			for _, comment := range cg.List {
				text := strings.ToLower(comment.Text)
				if strings.Contains(text, "ai-generated") ||
					strings.Contains(text, "generated by ai") ||
					strings.Contains(text, "copilot") ||
					strings.Contains(text, "chatgpt") ||
					strings.Contains(text, "claude") ||
					strings.Contains(text, "bard") {
					pos := fset.Position(comment.Pos())
					issues = append(
						issues, &Issue{
							File:       pos.Filename,
							Line:       pos.Line,
							Column:     pos.Column,
							Position:   pos,
							Type:       IssueAIGeneratedComment,
							Severity:   SeverityLevelLow,
							Message:    "AI-generated comment detected",
							Suggestion: "Review and improve AI-generated code",
							Code:       comment.Text,
						},
					)
				}
			}
		}
	}

	ast.Inspect(
		astNode, func(n ast.Node) bool {
			switch node := n.(type) {
			case *ast.FuncDecl:
				issues = append(issues, a.checkOverEngineering(node, fset)...)
				issues = append(issues, a.checkUnnecessaryComplexity(node, fset)...)
				issues = append(issues, a.checkAIPatterns(node, fset)...)
			case *ast.CallExpr:
				issues = append(issues, a.checkUnnecessaryReflection(node, fset)...)
				issues = append(issues, a.checkOverAbstraction(node, fset)...)
			case *ast.GenDecl:
				issues = append(issues, a.checkUnnecessaryInterfaces(node, fset)...)
			}
			return true
		},
	)

	return issues
}

func (a *AIBullshitAnalyzer) checkOverEngineering(fn *ast.FuncDecl, fset *token.FileSet) []*Issue {
	var issues []*Issue
	pos := fset.Position(fn.Pos())

	if fn.Name == nil || fn.Body == nil {
		return issues
	}

	funcName := fn.Name.Name

	// Check for design patterns that might be overused for simple tasks
	designPatterns := []string{
		"Factory", "Strategy", "Observer", "Visitor", "AbstractFactory",
		"Builder", "Singleton", "Adapter", "Bridge", "Composite",
		"Decorator", "Facade", "Flyweight", "Proxy", "Command",
	}

	for _, pattern := range designPatterns {
		if strings.Contains(funcName, pattern) {
			if len(fn.Body.List) < 5 {
				issues = append(
					issues, &Issue{
						File:       pos.Filename,
						Line:       pos.Line,
						Column:     pos.Column,
						Position:   pos,
						Type:       IssueAIOverengineeredSimple,
						Severity:   SeverityLevelHigh,
						Message:    "Over-engineered solution for simple task - AI bullshit detected",
						Suggestion: "Simplify: this function is too simple to need " + pattern + " pattern",
						Code:       "Function: " + funcName,
						WhyBad: fmt.Sprintf(
							`Using %s pattern for a %d-line function is overkill.
PROBLEMS:
• Unnecessary abstraction layers add complexity
• Extra allocations for interface dispatch
• Harder to understand and maintain
• Prevents compiler optimizations (inlining)
IMPACT: 10-20x more code, 2-5x slower execution
BETTER: Use direct function calls without patterns`, pattern, len(fn.Body.List),
						),
					},
				)
			}
		}
	}

	return issues
}

func (a *AIBullshitAnalyzer) checkUnnecessaryComplexity(fn *ast.FuncDecl, fset *token.FileSet) []*Issue {
	if fn.Name == nil || fn.Body == nil {
		return nil
	}

	var issues []*Issue
	metrics := a.analyzeComplexityMetrics(fn.Body)
	pos := fset.Position(fn.Pos())

	issues = append(issues, a.checkFactoryPatterns(fn, pos)...)

	if issue := a.checkNestingDepth(metrics.maxNestedDepth, pos, fn.Name.Name); issue != nil {
		issues = append(issues, issue)
	}

	if issue := a.checkInterfaceUsage(metrics.interfaceCount, len(fn.Body.List), pos, fn.Name.Name); issue != nil {
		issues = append(issues, issue)
	}

	if issue := a.checkReturnComplexity(metrics.returnCount, len(fn.Body.List), pos, fn.Name.Name); issue != nil {
		issues = append(issues, issue)
	}

	if issue := a.checkFunctionCount(metrics.funcCount, pos, fn.Name.Name); issue != nil {
		issues = append(issues, issue)
	}

	return issues
}

func (a *AIBullshitAnalyzer) checkAIPatterns(fn *ast.FuncDecl, fset *token.FileSet) []*Issue {
	var issues []*Issue

	if fn.Name == nil || fn.Body == nil {
		return issues
	}

	issues = append(issues, a.checkGoroutineOverkill(fn, fset)...)

	if fn.Doc != nil {
		for _, comment := range fn.Doc.List {
			text := strings.ToLower(comment.Text)
			if strings.Contains(text, "ai-generated") ||
				strings.Contains(text, "generated by ai") ||
				strings.Contains(text, "copilot") ||
				strings.Contains(text, "chatgpt") ||
				strings.Contains(text, "claude") ||
				strings.Contains(text, "bard") {
				pos := fset.Position(comment.Pos())
				issues = append(
					issues, &Issue{
						File:       pos.Filename,
						Line:       pos.Line,
						Column:     pos.Column,
						Position:   pos,
						Type:       IssueAIGeneratedComment,
						Severity:   SeverityLevelLow,
						Message:    "AI-generated comment detected",
						Suggestion: "Review and improve AI-generated code",
						Code:       comment.Text,
					},
				)
			}
		}
	}

	ast.Inspect(
		fn.Body, func(n ast.Node) bool {
			return true
		},
	)

	return issues
}

func (a *AIBullshitAnalyzer) checkGoroutineOverkill(fn *ast.FuncDecl, fset *token.FileSet) []*Issue {
	var issues []*Issue
	pos := fset.Position(fn.Pos())

	hasGoroutine := a.hasGoroutine(fn.Body)
	hasChannel := a.hasChannel(fn.Body)

	// AI bullshit: goroutine + channel for simple operations
	if hasGoroutine && hasChannel && len(fn.Body.List) < 10 {
		issues = append(
			issues, &Issue{
				File:       pos.Filename,
				Line:       pos.Line,
				Column:     pos.Column,
				Position:   pos,
				Type:       IssueAIGoroutineOverkill,
				Severity:   SeverityLevelHigh,
				Message:    "Using goroutines and channels for simple operation - AI bullshit",
				Suggestion: "Remove goroutines and channels, do it synchronously",
				Code:       "Function: " + fn.Name.Name,
			},
		)
	}

	return issues
}

func (a *AIBullshitAnalyzer) hasGoroutine(body *ast.BlockStmt) bool {
	found := false
	ast.Inspect(
		body, func(n ast.Node) bool {
			if _, ok := n.(*ast.GoStmt); ok {
				found = true
				return false
			}
			return true
		},
	)
	return found
}

func (a *AIBullshitAnalyzer) hasChannel(body *ast.BlockStmt) bool {
	found := false
	ast.Inspect(
		body, func(n ast.Node) bool {
			callExpr, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}

			ident, ok := callExpr.Fun.(*ast.Ident)
			if !ok || ident.Name != funcMake || len(callExpr.Args) == 0 {
				return true
			}

			if _, ok := callExpr.Args[0].(*ast.ChanType); ok {
				found = true
				return false
			}

			return true
		},
	)
	return found
}

func (a *AIBullshitAnalyzer) checkUnnecessaryReflection(call *ast.CallExpr, fset *token.FileSet) []*Issue {
	var issues []*Issue
	pos := fset.Position(call.Pos())

	funcName := getFuncNameFromCall(call)

	// If reflection is used for simple operations
	if strings.Contains(funcName, "reflect.") {
		reflectMethods := []string{"ValueOf", "TypeOf", "DeepEqual", "Select", "Call"}
		for _, method := range reflectMethods {
			if strings.Contains(funcName, method) {
				issues = append(
					issues, &Issue{
						File:       pos.Filename,
						Line:       pos.Line,
						Column:     pos.Column,
						Position:   pos,
						Type:       IssueAIUnnecessaryReflection,
						Severity:   SeverityLevelHigh,
						Message:    "Using reflection for simple operation - AI overkill",
						Suggestion: "Use direct type operations instead of reflection",
						Code:       "Call: " + funcName,
					},
				)
			}
		}
	}

	return issues
}

func (a *AIBullshitAnalyzer) checkOverAbstraction(call *ast.CallExpr, fset *token.FileSet) []*Issue {
	var issues []*Issue
	pos := fset.Position(call.Pos())

	funcName := getFuncNameFromCall(call)

	abstractionWords := []string{"Interface", "Abstract", "Factory", "Manager", "Handler", "Service", "Provider"}

	for _, word := range abstractionWords {
		if strings.Contains(funcName, word) {
			issues = append(
				issues, &Issue{
					File:       pos.Filename,
					Line:       pos.Line,
					Column:     pos.Column,
					Position:   pos,
					Type:       IssueAIOverAbstraction,
					Severity:   SeverityLevelMedium,
					Message:    "Potentially over-abstracted code - AI pattern",
					Suggestion: "Consider if this abstraction is really needed",
					Code:       "Call: " + funcName,
				},
			)
		}
	}

	return issues
}

func (a *AIBullshitAnalyzer) checkUnnecessaryInterfaces(gen *ast.GenDecl, fset *token.FileSet) []*Issue {
	var issues []*Issue
	pos := fset.Position(gen.Pos())

	if gen.Tok != token.TYPE {
		return issues
	}

	for _, spec := range gen.Specs {
		typeSpec, ok := spec.(*ast.TypeSpec)
		if !ok {
			continue
		}

		interfaceName := typeSpec.Name.Name

		overEngineeredPatterns := []string{
			"Factory", "AbstractFactory", "Builder", "Strategy",
		}

		for _, pattern := range overEngineeredPatterns {
			if strings.Contains(interfaceName, pattern) {
				issues = append(
					issues, &Issue{
						File:       pos.Filename,
						Line:       pos.Line,
						Column:     pos.Column,
						Position:   pos,
						Type:       IssueAIOverengineeredSimple,
						Severity:   SeverityLevelHigh,
						Message:    "Over-engineered solution for simple task - AI bullshit detected",
						Suggestion: "Simplify: consider if " + pattern + " pattern is really necessary here",
						Code:       "Type: " + interfaceName,
					},
				)
			}
		}

		interfaceType, ok := typeSpec.Type.(*ast.InterfaceType)
		if !ok {
			continue
		}

		if interfaceType.Methods == nil || len(interfaceType.Methods.List) != 1 {
			continue
		}

		bullshitPatterns := []string{"Provider", "Manager", "Handler", "Service"}

		for _, pattern := range bullshitPatterns {
			if strings.Contains(interfaceName, pattern) {
				issues = append(
					issues, &Issue{
						File:       pos.Filename,
						Line:       pos.Line,
						Column:     pos.Column,
						Position:   pos,
						Type:       IssueAIUnnecessaryInterface,
						Severity:   SeverityLevelMedium,
						Message:    "Single-method interface with generic name - possible AI bullshit",
						Suggestion: "Consider if this interface is really needed or use concrete type",
						Code:       "Interface: " + interfaceName,
					},
				)
			}
		}
	}

	return issues
}

func getFuncNameFromCall(call *ast.CallExpr) string {
	switch fun := call.Fun.(type) {
	case *ast.Ident:
		return fun.Name
	case *ast.SelectorExpr:
		if pkg, ok := fun.X.(*ast.Ident); ok {
			return pkg.Name + "." + fun.Sel.Name
		}
		return fun.Sel.Name
	}
	return ""
}

type complexityMetrics struct {
	maxNestedDepth int
	interfaceCount int
	returnCount    int
	funcCount      int
}

func (a *AIBullshitAnalyzer) analyzeComplexityMetrics(body *ast.BlockStmt) complexityMetrics {
	var metrics complexityMetrics
	nestedDepth := 0

	ast.Inspect(
		body, func(n ast.Node) bool {
			switch n.(type) {
			case *ast.BlockStmt:
				nestedDepth++
				if nestedDepth > metrics.maxNestedDepth {
					metrics.maxNestedDepth = nestedDepth
				}
			case *ast.InterfaceType:
				metrics.interfaceCount++
			case *ast.ReturnStmt:
				metrics.returnCount++
			case *ast.FuncLit:
				metrics.funcCount++
			}
			return true
		},
	)

	ast.Inspect(
		body, func(n ast.Node) bool {
			if _, ok := n.(*ast.BlockStmt); ok {
				nestedDepth--
			}
			return true
		},
	)

	return metrics
}

func (a *AIBullshitAnalyzer) checkFactoryPatterns(fn *ast.FuncDecl, pos token.Position) []*Issue {
	var issues []*Issue
	patterns := []string{"New", "Create", "Build", "Factory"}

	ast.Inspect(
		fn.Body, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}

			ident, ok := call.Fun.(*ast.Ident)
			if !ok {
				return true
			}

			for _, pattern := range patterns {
				if strings.Contains(ident.Name, pattern) {
					issues = append(
						issues, a.createComplexityIssue(
							pos, fn.Name.Name,
							"Complex pattern detected - possibly AI-generated overengineering",
							SeverityLevelHigh,
						),
					)
					break
				}
			}
			return true
		},
	)
	return issues
}

func (a *AIBullshitAnalyzer) checkNestingDepth(depth int, pos token.Position, funcName string) *Issue {
	if depth > 3 {
		return a.createComplexityIssue(
			pos, funcName,
			"Deeply nested function - likely overengineered",
			SeverityLevelHigh,
		)
	}
	return nil
}

func (a *AIBullshitAnalyzer) checkInterfaceUsage(interfaceCount, stmtCount int, pos token.Position, funcName string) *Issue {
	if interfaceCount > 0 && stmtCount < 10 {
		return a.createComplexityIssue(
			pos, funcName,
			"Using interfaces in simple function - unnecessary abstraction",
			SeverityLevelHigh,
		)
	}
	return nil
}

func (a *AIBullshitAnalyzer) checkReturnComplexity(returnCount, stmtCount int, pos token.Position, funcName string) *Issue {
	if returnCount > 2 && stmtCount < 10 {
		return a.createComplexityIssue(
			pos, funcName,
			"Multiple returns in simple function",
			SeverityLevelMedium,
		)
	}
	return nil
}

func (a *AIBullshitAnalyzer) checkFunctionCount(funcCount int, pos token.Position, funcName string) *Issue {
	if funcCount > 3 {
		return a.createComplexityIssue(
			pos, funcName,
			"Excessive use of nested functions/closures",
			SeverityLevelMedium,
		)
	}
	return nil
}

func (a *AIBullshitAnalyzer) createComplexityIssue(pos token.Position, funcName, message string, severity SeverityLevel) *Issue {
	return &Issue{
		File:       pos.Filename,
		Line:       pos.Line,
		Column:     pos.Column,
		Position:   pos,
		Type:       IssueAIUnnecessaryComplexity,
		Severity:   severity,
		Message:    message,
		Suggestion: "Consider simplifying this code",
		Code:       "Function: " + funcName,
	}
}
