// Code generated by "enumer -type=AnalyzerType -trimprefix Analyzer -transform=upper -json -text -yaml -sql"; DO NOT EDIT.

package analyzer

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _AnalyzerTypeName = "LOOPDEFEROPTIMIZATIONSLICEMAPSTRINGREFLECTIONINTERFACEREGEXTIMEMEMORYLEAKGCPRESSURESYNCPOOLGOROUTINECHANNELRACECONDITIONCONCURRENCYPATTERNSHTTPCLIENTHTTPREUSEIOBUFFERNETWORKPATTERNSDATABASESERIALIZATIONCRYPTOPRIVACYNILPTRCONTEXTERRORHANDLINGAPIMISUSEAIBULLSHITCGOTESTCOVERAGEDEPENDENCYCPUOPTIMIZATIONTYPEMAX"

var _AnalyzerTypeIndex = [...]uint16{0, 4, 21, 26, 29, 35, 45, 54, 59, 63, 73, 83, 91, 100, 107, 120, 139, 149, 158, 166, 181, 189, 202, 208, 215, 221, 228, 241, 250, 260, 263, 275, 285, 300, 307}

const _AnalyzerTypeLowerName = "loopdeferoptimizationslicemapstringreflectioninterfaceregextimememoryleakgcpressuresyncpoolgoroutinechannelraceconditionconcurrencypatternshttpclienthttpreuseiobuffernetworkpatternsdatabaseserializationcryptoprivacynilptrcontexterrorhandlingapimisuseaibullshitcgotestcoveragedependencycpuoptimizationtypemax"

func (i AnalyzerType) String() string {
	if i >= AnalyzerType(len(_AnalyzerTypeIndex)-1) {
		return fmt.Sprintf("AnalyzerType(%d)", i)
	}
	return _AnalyzerTypeName[_AnalyzerTypeIndex[i]:_AnalyzerTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AnalyzerTypeNoOp() {
	var x [1]struct{}
	_ = x[AnalyzerLoop-(0)]
	_ = x[AnalyzerDeferOptimization-(1)]
	_ = x[AnalyzerSlice-(2)]
	_ = x[AnalyzerMap-(3)]
	_ = x[AnalyzerString-(4)]
	_ = x[AnalyzerReflection-(5)]
	_ = x[AnalyzerInterface-(6)]
	_ = x[AnalyzerRegex-(7)]
	_ = x[AnalyzerTime-(8)]
	_ = x[AnalyzerMemoryLeak-(9)]
	_ = x[AnalyzerGCPressure-(10)]
	_ = x[AnalyzerSyncPool-(11)]
	_ = x[AnalyzerGoroutine-(12)]
	_ = x[AnalyzerChannel-(13)]
	_ = x[AnalyzerRaceCondition-(14)]
	_ = x[AnalyzerConcurrencyPatterns-(15)]
	_ = x[AnalyzerHTTPClient-(16)]
	_ = x[AnalyzerHTTPReuse-(17)]
	_ = x[AnalyzerIOBuffer-(18)]
	_ = x[AnalyzerNetworkPatterns-(19)]
	_ = x[AnalyzerDatabase-(20)]
	_ = x[AnalyzerSerialization-(21)]
	_ = x[AnalyzerCrypto-(22)]
	_ = x[AnalyzerPrivacy-(23)]
	_ = x[AnalyzerNilPtr-(24)]
	_ = x[AnalyzerContext-(25)]
	_ = x[AnalyzerErrorHandling-(26)]
	_ = x[AnalyzerAPIMisuse-(27)]
	_ = x[AnalyzerAIBullshit-(28)]
	_ = x[AnalyzerCGO-(29)]
	_ = x[AnalyzerTestCoverage-(30)]
	_ = x[AnalyzerDependency-(31)]
	_ = x[AnalyzerCPUOptimization-(32)]
	_ = x[AnalyzerTypeMax-(33)]
}

var _AnalyzerTypeValues = []AnalyzerType{AnalyzerLoop, AnalyzerDeferOptimization, AnalyzerSlice, AnalyzerMap, AnalyzerString, AnalyzerReflection, AnalyzerInterface, AnalyzerRegex, AnalyzerTime, AnalyzerMemoryLeak, AnalyzerGCPressure, AnalyzerSyncPool, AnalyzerGoroutine, AnalyzerChannel, AnalyzerRaceCondition, AnalyzerConcurrencyPatterns, AnalyzerHTTPClient, AnalyzerHTTPReuse, AnalyzerIOBuffer, AnalyzerNetworkPatterns, AnalyzerDatabase, AnalyzerSerialization, AnalyzerCrypto, AnalyzerPrivacy, AnalyzerNilPtr, AnalyzerContext, AnalyzerErrorHandling, AnalyzerAPIMisuse, AnalyzerAIBullshit, AnalyzerCGO, AnalyzerTestCoverage, AnalyzerDependency, AnalyzerCPUOptimization, AnalyzerTypeMax}

var _AnalyzerTypeNameToValueMap = map[string]AnalyzerType{
	_AnalyzerTypeName[0:4]:          AnalyzerLoop,
	_AnalyzerTypeLowerName[0:4]:     AnalyzerLoop,
	_AnalyzerTypeName[4:21]:         AnalyzerDeferOptimization,
	_AnalyzerTypeLowerName[4:21]:    AnalyzerDeferOptimization,
	_AnalyzerTypeName[21:26]:        AnalyzerSlice,
	_AnalyzerTypeLowerName[21:26]:   AnalyzerSlice,
	_AnalyzerTypeName[26:29]:        AnalyzerMap,
	_AnalyzerTypeLowerName[26:29]:   AnalyzerMap,
	_AnalyzerTypeName[29:35]:        AnalyzerString,
	_AnalyzerTypeLowerName[29:35]:   AnalyzerString,
	_AnalyzerTypeName[35:45]:        AnalyzerReflection,
	_AnalyzerTypeLowerName[35:45]:   AnalyzerReflection,
	_AnalyzerTypeName[45:54]:        AnalyzerInterface,
	_AnalyzerTypeLowerName[45:54]:   AnalyzerInterface,
	_AnalyzerTypeName[54:59]:        AnalyzerRegex,
	_AnalyzerTypeLowerName[54:59]:   AnalyzerRegex,
	_AnalyzerTypeName[59:63]:        AnalyzerTime,
	_AnalyzerTypeLowerName[59:63]:   AnalyzerTime,
	_AnalyzerTypeName[63:73]:        AnalyzerMemoryLeak,
	_AnalyzerTypeLowerName[63:73]:   AnalyzerMemoryLeak,
	_AnalyzerTypeName[73:83]:        AnalyzerGCPressure,
	_AnalyzerTypeLowerName[73:83]:   AnalyzerGCPressure,
	_AnalyzerTypeName[83:91]:        AnalyzerSyncPool,
	_AnalyzerTypeLowerName[83:91]:   AnalyzerSyncPool,
	_AnalyzerTypeName[91:100]:       AnalyzerGoroutine,
	_AnalyzerTypeLowerName[91:100]:  AnalyzerGoroutine,
	_AnalyzerTypeName[100:107]:      AnalyzerChannel,
	_AnalyzerTypeLowerName[100:107]: AnalyzerChannel,
	_AnalyzerTypeName[107:120]:      AnalyzerRaceCondition,
	_AnalyzerTypeLowerName[107:120]: AnalyzerRaceCondition,
	_AnalyzerTypeName[120:139]:      AnalyzerConcurrencyPatterns,
	_AnalyzerTypeLowerName[120:139]: AnalyzerConcurrencyPatterns,
	_AnalyzerTypeName[139:149]:      AnalyzerHTTPClient,
	_AnalyzerTypeLowerName[139:149]: AnalyzerHTTPClient,
	_AnalyzerTypeName[149:158]:      AnalyzerHTTPReuse,
	_AnalyzerTypeLowerName[149:158]: AnalyzerHTTPReuse,
	_AnalyzerTypeName[158:166]:      AnalyzerIOBuffer,
	_AnalyzerTypeLowerName[158:166]: AnalyzerIOBuffer,
	_AnalyzerTypeName[166:181]:      AnalyzerNetworkPatterns,
	_AnalyzerTypeLowerName[166:181]: AnalyzerNetworkPatterns,
	_AnalyzerTypeName[181:189]:      AnalyzerDatabase,
	_AnalyzerTypeLowerName[181:189]: AnalyzerDatabase,
	_AnalyzerTypeName[189:202]:      AnalyzerSerialization,
	_AnalyzerTypeLowerName[189:202]: AnalyzerSerialization,
	_AnalyzerTypeName[202:208]:      AnalyzerCrypto,
	_AnalyzerTypeLowerName[202:208]: AnalyzerCrypto,
	_AnalyzerTypeName[208:215]:      AnalyzerPrivacy,
	_AnalyzerTypeLowerName[208:215]: AnalyzerPrivacy,
	_AnalyzerTypeName[215:221]:      AnalyzerNilPtr,
	_AnalyzerTypeLowerName[215:221]: AnalyzerNilPtr,
	_AnalyzerTypeName[221:228]:      AnalyzerContext,
	_AnalyzerTypeLowerName[221:228]: AnalyzerContext,
	_AnalyzerTypeName[228:241]:      AnalyzerErrorHandling,
	_AnalyzerTypeLowerName[228:241]: AnalyzerErrorHandling,
	_AnalyzerTypeName[241:250]:      AnalyzerAPIMisuse,
	_AnalyzerTypeLowerName[241:250]: AnalyzerAPIMisuse,
	_AnalyzerTypeName[250:260]:      AnalyzerAIBullshit,
	_AnalyzerTypeLowerName[250:260]: AnalyzerAIBullshit,
	_AnalyzerTypeName[260:263]:      AnalyzerCGO,
	_AnalyzerTypeLowerName[260:263]: AnalyzerCGO,
	_AnalyzerTypeName[263:275]:      AnalyzerTestCoverage,
	_AnalyzerTypeLowerName[263:275]: AnalyzerTestCoverage,
	_AnalyzerTypeName[275:285]:      AnalyzerDependency,
	_AnalyzerTypeLowerName[275:285]: AnalyzerDependency,
	_AnalyzerTypeName[285:300]:      AnalyzerCPUOptimization,
	_AnalyzerTypeLowerName[285:300]: AnalyzerCPUOptimization,
	_AnalyzerTypeName[300:307]:      AnalyzerTypeMax,
	_AnalyzerTypeLowerName[300:307]: AnalyzerTypeMax,
}

var _AnalyzerTypeNames = []string{
	_AnalyzerTypeName[0:4],
	_AnalyzerTypeName[4:21],
	_AnalyzerTypeName[21:26],
	_AnalyzerTypeName[26:29],
	_AnalyzerTypeName[29:35],
	_AnalyzerTypeName[35:45],
	_AnalyzerTypeName[45:54],
	_AnalyzerTypeName[54:59],
	_AnalyzerTypeName[59:63],
	_AnalyzerTypeName[63:73],
	_AnalyzerTypeName[73:83],
	_AnalyzerTypeName[83:91],
	_AnalyzerTypeName[91:100],
	_AnalyzerTypeName[100:107],
	_AnalyzerTypeName[107:120],
	_AnalyzerTypeName[120:139],
	_AnalyzerTypeName[139:149],
	_AnalyzerTypeName[149:158],
	_AnalyzerTypeName[158:166],
	_AnalyzerTypeName[166:181],
	_AnalyzerTypeName[181:189],
	_AnalyzerTypeName[189:202],
	_AnalyzerTypeName[202:208],
	_AnalyzerTypeName[208:215],
	_AnalyzerTypeName[215:221],
	_AnalyzerTypeName[221:228],
	_AnalyzerTypeName[228:241],
	_AnalyzerTypeName[241:250],
	_AnalyzerTypeName[250:260],
	_AnalyzerTypeName[260:263],
	_AnalyzerTypeName[263:275],
	_AnalyzerTypeName[275:285],
	_AnalyzerTypeName[285:300],
	_AnalyzerTypeName[300:307],
}

// AnalyzerTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AnalyzerTypeString(s string) (AnalyzerType, error) {
	if val, ok := _AnalyzerTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AnalyzerTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AnalyzerType values", s)
}

// AnalyzerTypeValues returns all values of the enum
func AnalyzerTypeValues() []AnalyzerType {
	return _AnalyzerTypeValues
}

// AnalyzerTypeStrings returns a slice of all String values of the enum
func AnalyzerTypeStrings() []string {
	strs := make([]string, len(_AnalyzerTypeNames))
	copy(strs, _AnalyzerTypeNames)
	return strs
}

// IsAAnalyzerType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AnalyzerType) IsAAnalyzerType() bool {
	for _, v := range _AnalyzerTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AnalyzerType
func (i AnalyzerType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AnalyzerType
func (i *AnalyzerType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AnalyzerType should be a string, got %s", data)
	}

	var err error
	*i, err = AnalyzerTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for AnalyzerType
func (i AnalyzerType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AnalyzerType
func (i *AnalyzerType) UnmarshalText(text []byte) error {
	var err error
	*i, err = AnalyzerTypeString(string(text))
	return err
}

// MarshalYAML implements a YAML Marshaler for AnalyzerType
func (i AnalyzerType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for AnalyzerType
func (i *AnalyzerType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = AnalyzerTypeString(s)
	return err
}

func (i AnalyzerType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *AnalyzerType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of AnalyzerType: %[1]T(%[1]v)", value)
	}

	val, err := AnalyzerTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
